package:
  name: ginjinn
  version: {{ GIT_DESCRIBE_TAG }}

source:
#   git_rev:
  git_url: https://github.com/AGOberprieler/ginjinn

requirements:
  build:
    - python 3.6
    - protobuf 3.9.2
    - setuptools
    - numpy 1.16.5
    - pip
    - cython 0.29.13
    - importlib_resources
    - pillow

  run:
    - python 3.6
    - jinja2
    - pillow
    - requests
    - tensorflow_models
    - scikit-learn
    - protobuf 3.9
    - cython
    - pandas
    - numpy
    - matplotlib
    - importlib_resources
    - tqdm
    - pyyaml

build:
  skip: true # [not linux]
  entry_points:
    - ginjinn = ginjinn.__main__:main

# test:
#   imports:
#     -

about:
  home: https://github.com/AGOberprieler/ginjinn
  license: MIT
  summary: Object detection pipeline for the extraction of structures from digitized herbarium specimens