package:
  name: ginjinn
  version: {{ GIT_DESCRIBE_TAG }}

source:
#   git_rev:
  git_url: https://github.com/AGOberprieler/ginjinn

requirements:
  build:
    - python 3.6
    - setuptools
    - numpy
    - pip
    - cython
    - importlib_resources

  run:
    - python 3.6
    - tensorflow 1.14 
    - protobuf
    - tensorflow_models
    - numpy
    - pandas
    - matplotlib
    - importlib_resources
    - jinja2
    - scikit-learn
    - tqdm
    - pyyaml
    - requests

build:
  entry_points:
    - ginjinn = ginjinn.__main__:main

# test:
#   imports:
#     -

about:
  home: https://github.com/AGOberprieler/ginjinn
  license: MIT
  summary: Object detection pipeline for the extraction of structures from digitized herbarium specimens