package:
  name: tensorflow_models
  version: 1.11

source:
  - git_url: https://github.com/TankredO/models
    folder: models
  - git_url: https://github.com/cocodataset/cocoapi
    folder: cocoapi


build:
  skip_compile_pyc:
    - "*"

requirements:
  build:
    - python 3.6.*
    - cython 0.29.13
    - setuptools
    - numpy 1.16.5
    - git
    - pip
    - protobuf 3.9.2

  run:
    - python 3.6.*
    - cython 0.29.13
    - numpy 1.16.5
    - git
    - pip
    - protobuf 3.9.2

# test:
#   imports:
#     -

# about:
#   home: