package:
  name: tensorflow_models
  version: 1.11

source:
  - git_url: https://github.com/TankredO/models
    folder: models
  - git_url: https://github.com/cocodataset/cocoapi
    folder: cocoapi


build:
  skip_compile_pyc:
    - "*"

requirements:
  build:
    - python 3.6.*
    - cython
    - pillow
    - matplotlib
    - setuptools
    - numpy
    - git
    - pip
    - protobuf 3.9.*

  run:
    - python 3.6.*
    - cython
    - pillow
    - matplotlib
    - setuptools
    - numpy
    - git
    - pip
    - protobuf 3.9.*

# test:
#   imports:
#     -

# about:
#   home: