package:
  name: ginjinn
  version: 0.1

# source:
#   git_rev:
#   git_url:

requirements:
  build:
    - python 3.6.*
    - setuptools
    - protobuf 3.8.*

  run:
    - python 3.6.*
    - protobuf 3.8.*

# test:
#   imports:
#     -

# about:
#   home: