package:
  name: ginjinn
  version: 0.1.1

source:
#   git_rev:
  git_url: https://github.com/AGOberprieler/ginjinn

requirements:
  build:
    - python 3.6.*
    - setuptools
    - protobuf 3.8.*
    - tensorflow_models
    - numpy
    - pandas
    - pip
    - cython
    - pillow
    - matplotlib
    - cycler

  run:
    - python 3.6.*
    - protobuf 3.8.*
    - tensorflow_models
    - numpy
    - pandas
    - matplotlib
    - cycler

build:
  entry_points:
    - ginjinn = ginjinn.__main__:main

# test:
#   imports:
#     -

about:
  home: https://github.com/AGOberprieler/ginjinn
  license: MIT
  summary: Object detection pipeline for the extraction of structures from herbarium specimens