# ATTENTION: YAML is whitespace sensitive

# == Data configuration ==
# path to directory containing annotations (xml) or path of the VIA JSON annotations
# e.g. /home/me/data/annotations for linux, or C:\Users\me\Documents\annotations for windows
annotation_path: {{ config.annotation_path }}
# annotation type. ["PascalVOC", "VIA"]
annotation_type: {{ config.annotation_type }}

# path to directory containing annotated images (jpeg, png)
image_dir: {{ config.image_dir }}

# fraction of the data that should be used for evaluation [0.0-1.0]
test_fraction: {{ config.test_fraction }}


# == Model configuration ==
# name of the object detection model
# (or path to a tensorflow pipeline.config file)
model_name: {{ config.model_name }}

# whether a pretrained model checkpoint should be used
use_checkpoint: true
# path to pretrained model checkpoint. If empty and use_checkpoint is true
# a pretrained checkpoint will be downloaded, if available.
checkpoint_path: {{ config.checkpoint_path }}


# == Training and evalution configuration ==
# number of training iterations
n_iter: {{ config.n_iter }}

# number of images to evaluate at once
batch_size: {{ config.batch_size }}


# == Augmentation configuration ==
# augmentation can artificially "increase" your sample size by
# modifying the image before training. This can improve the robustness
# of the trained model, but increases the number of interations that is
# required for the model to converge and also increases the computation
# time. Augmentation is randomly applied to images.
augmentation:
    # flip images horizontally
    flip_horizontal:
      active: {{ config.augmentation.flip_horizontal.active }}
    # flip images vertically
    flip_vertical:
      active: {{ config.augmentation.flip_vertical.active }}
    # flip by 90 degrees
    flip_90:
      active: {{ config.augmentation.flip_90.active }}
    
    
    # change brightness
    change_brightness:
      active: {{ config.augmentation.change_brightness.active }}
      min_delta: {{ config.augmentation.change_brightness.min_delta }}
      max_delta: {{ config.augmentation.change_brightness.max_delta }}

    # change contrast
    change_contrast:
      active: {{ config.augmentation.change_contrast.active }}
      min_delta: {{ config.augmentation.change_contrast.min_delta }}
      max_delta: {{ config.augmentation.change_contrast.max_delta }}

    # jitter bounding boxes
    jitter_boxes:
      active: {{ config.augmentation.jitter_boxes.active }}
      ratio: {{ config.augmentation.jitter_boxes.ratio }}